### ISSUE TITLE
Bypass jurisdiction list if JA only has access to a single jurisdiction

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#1011]

**Comment by MorganLove** [comment]
@Jonah-Kagan could you expand on what you have in mind here?

**Comment by jonahkagan** [comment]
Sure, I was thinking that if a JA is only participating in a single audit in a single organization (which is probably the most common case), then when they log in, instead of seeing the home screen with just one jurisdiction on it (which they have to click), they could be routed directly to the JA audit screen.
