### ISSUE TITLE
JA UI/UX updates for ballot manifest and CVR labels/instructions

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1055]
Small updates to headers, copy, and sample files for the JA file upload screen:
1. Update BM header
2. Update BM copy
3. Update BM sample file
4. Update CVR header
5. Update CVR copy

See screenshot for actual text.
![Screen Shot 2021-03-08 at 3.10.58 PM.png](https://zube.io/files/votingworks/9855c5a23234e4b96809e633ce573345-screen-shot-2021-03-08-at-3-10-58-pm.png)

**Comment by MorganLove** [comment]
@mcchilders Just verifying, the sample file you want here is the same as for Ballot Comparison?

**Comment by mcchilders** [comment]
@MorganLove the CVR one is the same, the ballot manifest one is slightly different (see this card for example: https://zube.io/votingworks/arlo/c/1080)
