### ISSUE TITLE
Strip leading/following whitespace in ballot manifest/CVR files

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1104]
We should strip leading/following whitespace from all fields in the ballot manifest and CVR files, so that we don't have mismatches that are real but invisible to humans.

**Comment by jonahkagan** [comment]
This issue was being caused by not stripping whitespace in the CVR. Since the CVR is machine-generated, we don't expect whitespace issues. This only happened because we were manually creating CVR test files. So no change is needed.
