### ISSUE TITLE
Add "delete" function & confirmation modal for old audits

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1115]
From the View/Create New Audit screen, the AA should be able to delete any audit in their organization. Let's add a "delete" icon to the end of the buttons for each audit that, when clicked, triggers a confirmation modal where the AA can either cancel or confirm deletion of the audit. The modal should also warn the user that the action cannot be undone.

"Are you sure you want to delete <Audit Name?> This action cannot be undone. Cancel/Delete"

![Screen Shot 2021-03-19 at 2.52.04 PM.png](https://zube.io/files/votingworks/fd29f8feae587549e96f719844caa06a-screen-shot-2021-03-19-at-2-52-04-pm.png)

**Comment by MorganLove** [comment]
@Jonah-Kagan Do we have a delete endpoint for these? I was just looking in elections.py and only saw a POST endpoint. Or is there a different way we should be deleting these?

**Comment by jonahkagan** [comment]
We don't have an endpoint to delete audits yet
