### ISSUE TITLE
Remove consistent sampler from batch audits

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1181]
When running batch comp simulations on a statewide level, we've found that the consistent sampler increases the computational workload so much as to be functionally unusable. In addition, it's unclear that the sampler would ever deliver its desired effect (maximizing duplication of ballots selected across independent but overlapping contest samples) in its current form, since the sampler prohibits batch duplication and batch comp audits duplicate batches within the selection by design, to weight the batches appropriately.

PPEB already contains a sampling regimen, which we were augmenting with the consistent sampler, so we'll drop back to just using the PPEB standard.

**Comment by mcchilders** [comment]
@umbernhard this is done, yes?

**Comment by umbernhard** [comment]
@mcchilders yep
