### ISSUE TITLE
New design: Audit Board Data Entry screen

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1194]
Implement the new design for the Audit Board data entry screen.
![image (1).png](https://zube.io/files/votingworks/ef7b3687a7922ffa1dd875371eb76f60-image-1.png)

**Comment by MorganLove** [comment]
@mcchilders Just a quick point of clarification: I just noticed while implementing this that there is no 'back' button anymore to go to the previous ballot. Is this intentional? Or should I put that back in?

**Comment by mcchilders** [comment]
@MorganLove do you mean the "back to ballot list" button? (I don't think we have a button for going back to the previous ballot.)

Regardless, all the buttons need to stay with their existing functionality - so yep, let's put it back.

**Comment by MorganLove** [comment]
@mcchilders thanks! We did have a button for going to the previous ballot, so I'll put that back. :slightly_smiling_face:

**Comment by mcchilders** [comment]
@MorganLove can you show me which button you mean?
