### ISSUE TITLE
Add expected batch totals and discrepancy flag to audit report for batch comp

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1222]
In the audit report for ballot comparison, we include auditor input for all sampled ballots, the expected votes for those ballots, a flag for whether there's a discrepancy between the two, and an indication of the discrepancy (+/- 1/2).

In batch comparison audits, however, our audit report is currently showing only the auditor entries for a sampled batch. We'd like to add the rest of the data to the audit report, so that it also shows:
- expected totals for each sampled batch
- a flag if there's a discrepancy between a particular batch
-- if possible, some indication of what the max possible error/taint per batch w/discrepancies ... the math calculates this value so we should be able to pull it in

**Comment by jonahkagan** [comment]
started here: https://github.com/votingworks/arlo/compare/batch-tallies-in-report?expand=1
