### ISSUE TITLE
Activity log for AAs

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1239]
We'd like to be able to show AAs a log of all jurisdiction activity in an audit, including logins. It should be on its own page in the app.

TBD: where should this log live? An additional top-level nav item for Audit Activity, maybe? TBD, open to suggestions.

**Comment by jonahkagan** [comment]
Possible API that would do this: https://auth0.com/docs/logs/retrieve-log-events-using-mgmt-api
