### ISSUE TITLE
Hart CVR parser in Arlo (we have a script)

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1248]
Conditions of Acceptance:
- Allow JA to specify that a CVR is a Hart CVR at time of upload
-  Accept a (likely zipped file folder) collection of individual CVR files as the file upload and parse into our data format (e.g. having Arlo run the script that we currently run outside Arlo for Hart files). 
- Store both the original and the parsed versions for posterity, in case we need to prove they're the same (or troubleshoot parsing in future)

Sample files:
https://drive.google.com/drive/u/0/folders/1HEeeXSVJhjgVKAQIAE-E3GwTCypHWwOq

**Comment by mcchilders** [comment]
At this point we have not found any combination of Hart exports (individual CVR files plus add'l reports) that allows us to know which tabulator a ballot was scanned by, and since batch names are duplicated across tabulators, we don't have enough data to use these files absent a human adding data.

**Comment by rsmith1302** [comment]
I'm not familiar with this project, so I might be misinterpreting the issue, but I've written a Hart CVR parser. The expoted PDF (but not the XML) contains a DeviceSerial field that will identify the scanner. I use pdfgrep to extract the metadata from the PDF.

**Comment by jonahkagan** [comment]
Thanks for the tip @rsmith1302!
