### ISSUE TITLE
Use QR codes for audit board login/auth

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#127]
**User Story:** As a user I would like a simplified way to log each audit board in to their respective data entry interface, so that if I have a lot of boards (or limited time) I can do so efficiently while still getting the boards to the correct place.

**Background:** Once we have a data entry interface for each audit board, we will need a way to authenticate users and direct them to the correct interface for their particular audit board. Persistent login schemes are less than ideal since users are one-time volunteers and co-located with the election official, and we'd like to improve on CORLAs model of making the election official responsible for logging each audit board on to their device (cumbersome, makes less sense if we start seeing boards that want to enter data on their personal phones.) Providing QR codes that the election official can print and distribute still gives us the necessary security while minimizing overhead/upkeep that traditional login schemes require.

**Requirements:**
- Add an additional button below the "Download retrieval list" button in the UI, labeled "Download Audit Board Credentials for Data Entry"
- When clicked, the button should generate a PDF containing 1 page per audit board, labeled with:
-- Audit board name
-- Basic instructions
-- QR code that contains both the website URL of that board's data entry interface and whatever hash/code (if any) they need to authenticate
-- The human-friendly version of that URL
(see screenshot)
 **NOTE: Audit board credentials should be audit-specific, not round-specific, so they'll only need to be shown as we create Round 1.

**Open questions:** 
- The human-friendly URL in the mockup is an idea based on what we've discussed, but I'm not tied to it. If there's a good reason to do something other than "random series of words" for that URL, let's discuss!
- Sizing of the QR code (and really all the QR code details are up to the implementer - the screenshots are meant to give you an idea, not be prescriptive.

<img width="777" alt="Screen Shot 2019-09-11 at 9 52 34 AM" src="https://user-images.githubusercontent.com/50123300/64717312-0e324500-d492-11e9-8b39-c9a9e86da9a1.png">
<img width="657" alt="Screen Shot 2019-09-11 at 10 07 11 AM" src="https://user-images.githubusercontent.com/50123300/64717313-0e324500-d492-11e9-91a7-742bd64d0d1a.png">

**Comment by mcchilders** [comment]
Ok @MorganLove, did some testing and  it looks like what's on staging still has a couple pieces missing. Can we please: 
- remove the onscreen QR codes display (great for testing tho!)
- implement the downloadable PDF pages w/the QR code/instructions/etc for audit board login, 1 per audit board, as described above
- make the URLs for the audit boards human-friendly, as described above (They still look like this rt now: "https://vx-arlo-staging.herokuapp.com/election/2ec74b81-7241-43e3-9c81-cd214655e6a5/board/3de227f4-efa1-4882-998c-af56f84549d9" and no one will be able to successfully type that in if they aren't using the QR code ;)

**Comment by mcchilders** [comment]
@MorganLove I'm also realizing that it may not have been obvious, because white backgrounds on pictures, that there are actually two mockups here - the top one is the onscreen implementation (download button) and the bottom one is a mockup of what the PDF page for a single audit board would look like. In case that makes it clearer!)

**Comment by MorganLove** [comment]
> Ok @MorganLove, did some testing and it looks like what's on staging still has a couple pieces missing. Can we please:
> 
> * remove the onscreen QR codes display (great for testing tho!)
> * implement the downloadable PDF pages w/the QR code/instructions/etc for audit board login, 1 per audit board, as described above
> * make the URLs for the audit boards human-friendly, as described above (They still look like this rt now: "https://vx-arlo-staging.herokuapp.com/election/2ec74b81-7241-43e3-9c81-cd214655e6a5/board/3de227f4-efa1-4882-998c-af56f84549d9" and no one will be able to successfully type that in if they aren't using the QR code ;)

Hi there, @mcchilders @benadida for human readable URLS we would need the human readable url generated from the back end as a part of the audit board model. We could have a slug that is created in the server side and then used on fe as a part of our redirect.

**Comment by mcchilders** [comment]
@MorganLove are you waiting on the endpoint for passing in the slug and getting back the real URL?

**Comment by benadida** [comment]
@MorganLove @mcchilders I've prepared a small PR that automatically generates audit board passphrases made of 4 english words with dashes when the audit boards are created, and then redirects `/auditboard/<passphrase>` to the right place. 

https://github.com/votingworks/arlo/pull/241

**Comment by mcchilders** [comment]
waiting for: @ben needs to add tweak to make sure we don't have passphrase collisons
@monica will check to make sure the xkcd library is sfw

**Comment by benadida** [comment]
fix is in for no passphrase collision, but some code merge messiness needs to be cleaned up before we can merge.
