### ISSUE TITLE
Improved naming of retrieval list

### ISSUE THREAD

**Issue by umbernhard** [votingworks/arlo#136]
We should use the election name/race name in the naming of the retrieval list file. Currently it just gives us `ballot-retrieval-jurisdiction-1-1.csv`, would be great if it were `ballot-retrieval-Washtenaw-1-1.csv`.

**Comment by eventualbuddha** [comment]
> @eventualbuddha could we also apply that to the audit report? Currently it's just `audit-report`...

https://github.com/votingworks/arlo/pull/195
