### ISSUE TITLE
Fix map bugs (VA)

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1406]
Because the jurisdiction names in the source mapping file don't have the jurisdiction type in the name (e.g. "Richmond" instead of Richmond City, Richmond County) we aren't correctly mapping: 

- anything that is a City
- anything that has two entries, a City and a County

We have logic to expect the word "County" to be added to the jurisdiction in the participating jurisdictions file, so that's why those work fine. 

Suggested fix: add the word "City" to the cities in the source mapping file, then add logic that says if the word "City" is present to not expect "County" to be added?

![Screen Shot 2022-01-14 at 11.48.53 AM.png](https://zube.io/files/votingworks/fcbb4b489f32e756d8261ab198a26a53-screen-shot-2022-01-14-at-11-48-53-am.png)

**Comment by mcchilders** [comment]
https://en.wikipedia.org/wiki/List_of_cities_and_counties_in_Virginia#List_of_independent_cities

**Comment by jonahkagan** [comment]
Implementation plan:
- Add "Richmond City" to our list of geographies
- Change our jurisdiction name checking logic to look for exact matches first, then use the "<jurisdiction name> County" heuristic as a second check
- (Optionally) Show extra manually added geographies as separate boxes in the map

**Comment by mcchilders** [comment]
[Va Jurisdiction Names.csv](https://github.com/votingworks/arlo/files/8156082/Va.Jurisdiction.Names.csv)
