### ISSUE TITLE
Modify instructions on audit board credentials PDF

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1428]
**Description:**
Add wording to the instructions on the PDF of audit board credentials that indicates the credentials  should not be shared publicly.

**Background:**
Audit boards are responsible for examining physical ballots and reporting what they see on each ballot in the audit tool, and need to be authenticated. However, the identity of the audit board members is not fixed until the audit starts (e.g. the admin might know that they'll need 10 teams of two people, or 10 audit boards, but who will sit on each board isn't decided until the day of the audit based on who shows up), and the members only act as a team. Audit boards usually authenticate once or a few times during the day of the audit, but never again, and they perform the audit in the same physical space as the Jurisdiction Administrator. Given the need for authentication only in these limited circumstances, we use a physical login credential for each audit board - a PDF with a QR code (URL with token) that can be provided to the audit board by the jurisdiction administrator when it's time for them to log in.

Unfortunately, in an effort to be transparent, we have seen people show these QR codes publicly, which defeats the purpose as a secure authentication mechanism. We should add warning language to the PDF that indicates the audit board should keep their credential private.

**Comment by ginvdr** [comment]
Wording recommendation:  Keep secure!  Only share login credentials with jurisdiction managers and audit board members.  Do not post publicly.

A bigger bold font would be good too.
