### ISSUE TITLE
Batch Comp: Add ability to edit batch totals

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1429]
Right now we assume that all the batch totals are being entered once, when they are finished, and never again. There are cases where admins might want to enter some batch totals and not others, though, or edit already-entered batch totals. 

To accommodate, we should move to letting AAs enter/save/edit any batch total individually, and separate submitting the entire page so that can serve as the final signal that the AA is done.

**Comment by ginvdr** [comment]
@jonahkagan - I think this has been done?
