### ISSUE TITLE
Support user: make list of audits more manageable

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1433]
The current list of orgs and audits in those orgs that the support user sees (and has to scroll through) is getting really long and unwieldy. We can solve this by:

- highlighting recent/current audits at the very top
- hiding older audits automatically / behind some collapsable 
- making audits collapsible by org

Let's discuss the best way to go here.

**Comment by mattroe** [comment]
From sync discussion: proposed solution to filter for active audits with some limited audit status.

**Comment by arsalansufi** [comment]
- [ ] Add "Log in as" buttons that log you in as an audit admin _and_ navigate to a specific audit
- [ ] Explore pinning
- [ ] Explore search bar

Relevant Slack thread: https://votingworks.slack.com/archives/CKCVA0F9S/p1661897867743139

**Comment by arsalansufi** [comment]
Another piece of context: Until very recently, Ginny had been relying on the audit admin UI (as an audit admin in nearly every active org) but just recently switched to the support user UI. So we're now collecting real feedback from Ginny on support user pain points

**Comment by benadida** [comment]
My sense on this one is that if we prioritize current audits over old ones, this might solve 90+% of the problem?

**Comment by mattroe** [comment]
[Latest description of the problem](https://docs.google.com/document/d/1FjXSCCCq1EV8VFr6EXcjXXIvMoX3l7ixcWx3PYk7FKw/edit?usp=sharing) courtesy of @ginvdr

**Comment by mattroe** [comment]
9/6 chat:
- what's the definition of an active audit?
- sort based on last updated
