### ISSUE TITLE
Batch Comp: Allow JAs to upload batch totals OR a complete CVR

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#1435]
In some voting systems, it's easier to get the full CVR export file than it is to get a breakdown of candidate totals by batch. If we were to allow JA's participating in batch comparison audits to choose which one they wanted to upload for their particular jurisdiction, we could parse the data from the CVRs to create the equivalent of a batch totals report ourselves.

We could potentially also parse a different system export of the candidate totals by batch (e.g. a PDF) depending on what the voting system produces.

**Comment by mattroe** [comment]
Closing this until @umbernhard determines if we want to generalize the Georgia feature for other customers.
