### ISSUE TITLE
Allow splitting of batch data entry and do the math in Arlo

### ISSUE THREAD

**Issue by benadida** [votingworks/arlo#1443]
In batch audits, some batches are large and thus, for practicality, are split up between different audit boards for counting. Right now, that means that jurisdictions have to do the math themselves to combine those batch tally sheets.

![butwhy](https://user-images.githubusercontent.com/18057/160626532-1d1ddb0b-dd23-49a9-9e45-745f132cb78b.gif)

Let's instead allow them to enter as many batch tally sheets as they would like for a given ballot, and sum them up. This is a little bit tricky in the UX because we want to make it clear that it's a separate tally sheet, not one that replaces the previous one. Suggested flow, for discussion:

- when entering a batch tally sheet, explain that it's okay to enter a partial batch tally.
- if the total number of ballots does not equal the batch, allow the addition of a new batch tally sheet for that same batch.
- once enough batch tallies have been entered, don't allow the addition of more batch tally sheets for that batch.
- allow editing of the batch tally sheets, cause typos, before final confirmation.

**Comment by jonahkagan** [comment]
Another possible solution is to have an audit board interface for batch comparison

**Comment by jonahkagan** [comment]
Discussed more and decided that the original solution of being able to enter multiple tally sheets for one batch solves the immediate problem. It will probably be useful to enter tally sheet names to keep track of them.
