### ISSUE TITLE
Implement flow for rolling back from round 2

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#1499]
Support Users should be able to:
- Undo the round start for any round of the audit
- Reopen rounds that have completed

We sometimes need to do this manually/using scripts when an audit gets stuck in a bad state due to auditing mistakes.

**Comment by arsalansufi** [comment]
Updated plan after discussion in Slack:

- Allow support users to roll back an audit to a previous round (two things happening under the hood, undoing current round start and re-opening previous round)
- Allow audit admins to reopen audit boards

Full Slack thread for context: https://votingworks.slack.com/archives/CKCVA0F9S/p1660838320351479
