### ISSUE TITLE
Upgrade Heroku stack

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#1502]
Heroku-18, our current stack, is deprecated and will be EOL'ed on April 30th, 2023. Upgrade instructions here: https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack

**Comment by umbernhard** [comment]
I've started doing some diggin on this task to assess how to scope it. Here's what I've found so far:

* Ubuntu 22.04, on which the heroku stack is based, only packages python 3.10 by default
* python 3.10 breaks a ton of stuff
* bumping dependency versions for things like `sqlalchemy` seems to have broken some of our DB tests (specifically about what results in a null from the DB)
* [consistent_sampler](https://github.com/votingworks/consistent_sampler) is not compatible with python 3.10 (the `collections` library's interface has changed)

**Comment by umbernhard** [comment]
This has been deferred by #1791. A new issue tracking Python versioning is #1792.
