### ISSUE TITLE
Audit progress: persist filter and sort in URL

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#1513]
Sometimes audit admins and/or support users want to focus on tracking the progress of a particular jurisdiction (or a few particular jurisdictions). For audits with many jurisdictions, it can be difficult to continually sort through the table to find those jurisdictions. We could help address this with a feature to pin jurisdictions to the top.

**Comment by mattroe** [comment]
9/6 sync:
- persisting filter and sort and creating a shareable/reference URL would likely address the problem
