### ISSUE TITLE
Home screen: more useful audit list

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#1515]
Currently, audits are ordered alphabetically. That's consistent, which is nice, but not always the most useful.

Some ideas for how to make it more useful:
- Show most recently created audits first
- Figure out a way to separate out active from inactive audits (e.g. maybe audits that haven't been logged into in a while could be inactive)
- Allow pinning an audit to the top of the list
- Show the current status/progress of each audit

**Comment by umbernhard** [comment]
Closing this as a duplicate of https://github.com/votingworks/arlo/issues/1433
