### ISSUE TITLE
Delayed tabulation ballot comparison audits (unblock OC)

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#1523]
Figure out a way to support ballot comparison audits where not all of the ballots are tabulated yet at the start of the audit.

**Comment by jonahkagan** [comment]
An idea:
- Run a ballot comparison audit on the main chunk of ballots (that have been tabulated already)
- Wait til the rest of the ballots are tabulated, then run a ballot polling audit on those ballots
- Write a script to export the audit results from the Arlo db and feed them into the SUITE p-value calculator

**Comment by umbernhard** [comment]
Just a progress update: the script works and is tested for one contest. I am working on porting it to more than one contests (the logic is done, just trying to test it now, which is challenging).
