### ISSUE TITLE
Batch comparison: make it easy to select from large number of batches when entering audit results

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#1527]
Add a filter to the batch audit result entry table. Filter batches by name. Follow the design pattern of the jurisdiction progress table filter. One improvement to that pattern: Include an inset X button on the right to clear the filter.

An open question: what happens to the "Choice Total Votes" row at the bottom when batches are filtered? Does it update with filtered totals? Should we just not show it?

For now, don't worry about filtering by audit boards as @ginvdr suggested below, since we are still figuring out that concept.

**Comment by ginvdr** [comment]
If using audit boards, need a filter by audit board too.

**Comment by arsalansufi** [comment]
This will actually be covered as part of https://github.com/votingworks/arlo/issues/1623 so going to close this issue out!
