### ISSUE TITLE
Prevent race conditions between dependent file uploads

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#1532]
If a jurisdiction reuploads its ballot manifest while its CVR file is processing, this can cause a race condition since the batches will be deleted and recreated in the database. In general, file uploads for a jurisdiction should not be allowed to occur simultaneously. This includes automatic reprocessing of files (e.g. when CVR automatically reprocessed on manifest upload).

**Comment by jonahkagan** [comment]
Another related race condition: In the batch inventory flow, if a user uploads a CVR file and then deletes a tabulator status file before reprocessing starts, the worker will fail to find the tabulator status file in the db and error unexpectedly. (This could also happen with any other dependent files.)

**Comment by jonahkagan** [comment]
Another example that occurred: A user deleted the batch tallies file while it was queued to be reprocessed, and when the task reached the worker, it failed due to a missing batch tallies file in the db.

**Comment by eventualbuddha** [comment]
Noting that this is only partially fixed. In particular, deleting files that a currently-processing file needs to reference is not blocked in most cases. cc @arsalansufi to re-prioritize

**Comment by jonahkagan** [comment]
Given that we've been switching most of the file upload UI to only have a delete button, rather than a replace button, I think it's important to handle the delete cases as well. I'd like to reopen and make sure we handle those cases too.
