### ISSUE TITLE
Print audit board signs for sort-and-stack auditing

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#1547]
![image](https://user-images.githubusercontent.com/530106/178799704-389cf0e9-aef6-45c1-b51d-5c39277ffb72.png)

This applies in batch comparison audits specifically.

**Comment by ginvdr** [comment]
https://docs.google.com/document/d/1f0jQ2h_T4LkpEkzWpIYoWiNPkNLiNowbJiinx6sk41E/edit?usp=sharing
