### ISSUE TITLE
Write-in choices for audit boards

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#1549]
## Problem
Currently, Arlo doesn't have any built-in support for write-ins. Instead, we recommend that audit admins add a "write-in" contest choice when setting up contests (see [docs](https://docs.voting.works/arlo/audit-administrator/ballot-manifest/target-contests)).

This has caused a problem in ballot comparison audits specifically, since a write-in may be adjudicated as valid (counting as a vote) or invalid (counting as an undervote). If the CVR has a write-in that was invalid but the audit board selects the "write-in" choice, it creates a discrepancy.

We need a way for audit boards to be able to easily specify if a write-in was valid or invalid so that we can correctly compare the audit board's interpretation to the CVR.

 ## Proposed solution

Add an "Invalid Write-In" choice to the audit board ballot auditing screen. When this choice is selected, it should count as a vote for no candidate. If auditing a vote-for-1 contest, this is the same as a blank vote. If auditing a vote-for-n contest, the invalid write-in should simply be ignored.

This logic should apply for ballot comparison, ballot polling, and hybrid audits.

The audit report should show that the audit board selected invalid write-in.

Bonus: only show the "Invalid Write-In" choice if the audit admin added a write-in choice for the contest (e.g. if there's a choice that fuzzy matches the string "write-in" among the contest choices)

![Image](https://user-images.githubusercontent.com/530106/186234691-66d27d3f-53c7-4555-8122-f58018f7aa6a.png)

**Comment by umbernhard** [comment]
What @jonahkagan's proposing is probably the best way to handle it but that may not always be the way that corresponds to a jurisdiction's adjudication rules. I think we may need to dig into that a bit more. 

Question for @ginvdr about how to handle these: I think the rules in various jurisdictions may differ on whether the presence of an invalid write-in vote would nullify another vote. I believe this may be a sticking point in Michigan, specifically?

**Comment by ginvdr** [comment]
In Michigan's case (and I think they are the one with the oddest rule here), the invalid write-in would actually award the vote to another candidate in the case of an overvote and I don't think they'd use this button but the button for the other candidate.  We may need to worry about it if they ever end up doing ballot comparison but I think that's a long way off.

**Comment by arsalansufi** [comment]
Didn't tackle the "bonus" piece and opened a separate issue for that (https://github.com/votingworks/arlo/issues/1589) so we can close this one out!
