### ISSUE TITLE
Support user: improve Support user flow for navigating between AA and JM sessions

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/arlo#1750]
support tools feedback - navigating logging in back and forth between an audit admin and a jurisdiction manager is a lot of clicks - either using the back button or starting over by going to the org screen.  Am I missing something?

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/C01F2CH62TS/p1664371529164859?thread_ts=1664371529.164859&cid=C01F2CH62TS

**Comment by ginvdr** [comment]
Resolved with last round of support user improvements.
