### ISSUE TITLE
Improve setup blocking on manifest uploads

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/arlo#1765]
It was not clear to me until I saw an error message when clicking “Launch Audit” that jurisdictions uploading their ballot manifests was a prerequisite to launching the audit. I wanted to feel like I was done setting everything up with some completion button after going through this setup :disappointed:.

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/C01F2CH62TS/p1667427993551099?thread_ts=1667427993.551099&cid=C01F2CH62TS

**Comment by umbernhard** [comment]
Additional feedback from @mattroe https://votingworks.slack.com/archives/C01F2CH62TS/p1667703663700989

**Comment by umbernhard** [comment]
Duplicate of https://github.com/votingworks/arlo/issues/1544
