### ISSUE TITLE
Selecting the state should come earlier in the setup process

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/arlo#1772]
When we re-evaluate audit setup flow, selecting the state should come earlier in the process so a. the pretty map shows up and b. we don't have to enter fake data (random seed) to save it.

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/C01F2CH62TS/p1668532604743989

**Comment by umbernhard** [comment]
Alternatively, we could automatically assign a state to each audit organization since that's the most common use case.

**Comment by umbernhard** [comment]
https://votingworks.slack.com/archives/C01F2CH62TS/p1669836150544589
