### ISSUE TITLE
AA: provide jx-sample info before launching audit

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/arlo#1773]
Summary from [Arlo Product Improvements](https://docs.google.com/document/d/16wlZblYvuDUKPUF0rvHPO1YhMP_Z4zdsLqF2tisGHJs/edit#heading=h.ln9exyh772gu):

> Georgia’s November audit failed to launch, due to some jurisdiction managers uploading batch totals files that were in a different format than we expected. This type of issue has been a frequent occurrence across the lifespan of Arlo, with customers like Pennsylvania, Georgia, and Michigan running into errors that are only uncovered by launching the audit. In short, we can’t plan for weird customer input, so we should give ourselves the opportunity to detect it without making it public first. We should have a “pre-launch” phase, that runs the logic that launches an audit (parsing all the JM files, building the full dataset needed for sampling, and drawing the sample) but without notifying JMs until an official launch is executed. 

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/C01F2CH62TS/p1668708000948369

**Comment by mattroe** [comment]
@ginvdr to write down the list of problems and use cases that more insight before an audit could solve

**Comment by mattroe** [comment]
From 9/6 sync:
- No need for additional information that is not already presented. Possible solution could be presenting audit progress screen with an official start audit.
- So much anxiety for hitting the launch button in a statewide. One more step would alleviate that.
- In Georgia, looking at the number of batches per jurisidiction would have addressed this, which is shown on the audit progress screen.
