### ISSUE TITLE
JM screen has a typo in batch comparison audits if no batches are selected

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/arlo#1774]
This screen should say "batches" not "ballots"
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/2686765/209452416-f30b8c9b-d8ed-4e46-a7d5-3542ec0b06bb.png">

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/C01F2CH62TS/p1668794864575499

**Comment by umbernhard** [comment]
Should say "batches"

**Comment by jonahkagan** [comment]
This is intentional, I think "ballots" makes sense here. Recommend closing

**Comment by arsalansufi** [comment]
Agreed with your take @jonahkagan - so closing out
