### ISSUE TITLE
Support user: create a "download audit report" button that's clickable at any point during the audit

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/arlo#1775]
Issue automatically created from slack feedback reported by bernhard 
https://votingworks.slack.com/archives/C01F2CH62TS/p1669063695531989?thread_ts=1669063695.531989&cid=C01F2CH62TS

**Comment by umbernhard** [comment]
@ccombs-sqsp if you want a slightly less-involved UI/download thing to warm up to #1520, maybe try this one?

**Comment by combscCode** [comment]
oh btw if you want to ping me, ping me at @combscCode! Not a big deal either way, but the other one is used mostly for work.

**Comment by jonahkagan** [comment]
I think this was solved by adding the discrepancy report feature @arsalansufi. I'm gonna close it but let me know if you think otherwise

**Comment by arsalansufi** [comment]
Agreed!
