### ISSUE TITLE
Full screen modal for seed input

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/arlo#1777]
After visually sharing the data field for the random seed and then the review screen.... these both need to look better on a monitor.  And the random seed needs it's own "view" so people aren't asking questions about the other selections.

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/C01F2CH62TS/p1670983234762699

**Comment by nbhatia823** [comment]
Also, update the seed input copy which is currently unclear: 
![](https://files.slack.com/files-pri/TE6RHHERY-F07S4TSF9SR/screenshot_2024-10-16_at_3.31.23___pm.png)

> Could I update the copy to say Enter random characters instead of Enter the random characters? This threw me off as it sounds like there is a specific character set that needs to be entered (unless that is the case :sweat_smile:). Plus maybe some guidance on minimum string length
