### ISSUE TITLE
Improve CVR data validation for candidate names across jurisdictions

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/arlo#1780]
We need a way to prevent CVR-based audits from being set up incorrectly if jurisdictions have differing candidate names in their CVRs for the same contest (e.g. diff spelling or case).

See thread below for an example of this going wrong: https://votingworks.slack.com/archives/C013V6CT9H9/p1671038373066389

Issue automatically created from slack feedback reported by jonah 
https://votingworks.slack.com/archives/C01F2CH62TS/p1671045929426709

**Comment by mattroe** [comment]
Tagging as end of January to support first ballot comparison audits (NV)

**Comment by jonahkagan** [comment]
Some past context: https://votingworks.slack.com/archives/CKCVA0F9S/p1640040419002000
