### ISSUE TITLE
CVR upload: support NV ES&S

### ISSUE THREAD

**Issue by mattroe** [votingworks/arlo#1809]
[Problem summary](https://docs.google.com/document/d/15rVW8OPNjnvegeITgZg2o_QY6NbCRrzcsGjx0IfjpEw/edit?usp=sharing)

**Comment by mattroe** [comment]
@ginvdr link to example files

**Comment by mattroe** [comment]
next step: @ginvdr determine if the pipe-delimiting solution is viable

could we get info on the step by step process of the flow for exporting?

**Comment by mattroe** [comment]
call notes: https://votingworks.slack.com/archives/C013V6CT9H9/p1694030207355219

**Comment by arsalansufi** [comment]
Decided for now that https://github.com/votingworks/arlo/pull/1873 poses more risk than it's worth.

The current plan is now as follows: If Nevada runs into CVR upload errors, we'll ask them to try the Excel workaround. If that doesn’t work, we'll use our script workaround.

**Comment by arsalansufi** [comment]
Okay looks like the Excel workaround will work! Exporting from ES&S as an Excel file and then saving that Excel file as a CSV results in a properly quoted CSV for Lander (the county that had trouble last time around). FWIW they've only shared a CVR file with us and not a ballot information file, but we have every reason to believe that the workaround should work for the ballot information file, too. Closing this out accordingly
