### ISSUE TITLE
Discrepancy tracking

### ISSUE THREAD

**Issue by mattroe** [votingworks/arlo#1813]
[Discrepancy tracking brief](https://docs.google.com/document/d/1mtEOX-oWQyocOmLjFoPLAPJjbcRPEg_aIAXAFsoOeXY/edit?usp=sharing)

**Comment by mattroe** [comment]
@ginvdr to define the process of how the support team investigates discrepancies today step-by-step and insights from the user groups

**Comment by mattroe** [comment]
- Priority of subproblems: surfacing info > tracking comms/resolution; audit board discrepancies > file upload
- Examples of discrepancy tracking: https://docs.google.com/spreadsheets/d/1IT-AJrBm09qH3v8JL-m-V6iWZvITgvEr_V-YfAiuGso/edit#gid=867755159 & https://docs.google.com/spreadsheets/d/1R5pO_dmzCOMp-33Y1DuAIMrbDGhicIVG20RitC0O6ZM/edit#gid=0
- Seems important to have an active resolution flow
- Should we prototype this out of the system? Is the live update actually the root issue?
- Ginny pulls this report every 30m for some active large audits
- General consensus it is worth tackling the spreadsheet before building out an interface to test the problem
- Agreement to show human and RLA math discrepancies

**Comment by jonahkagan** [comment]
Initial scope: A spreadsheet download that helps support users track audit board discrepancies in a more streamlined way.

**Comment by jonahkagan** [comment]
New scope:
- An indicator of which jurisdictions have discrepancies in the progress screen
- A button for audit admins to download the discrepancy report
