### ISSUE TITLE
Support tools: progress status indicator and audit type 

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/arlo#1843]
A status flag by each audit indicating the audit status/round would be really helpful in the support tools list of active audits.
In the support admin user view make the follow UI improvements:
- Add the status for each audit 
- Add the round for each audit 
- Order the audits by creation date with the most recent at the top 

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/C01F2CH62TS/p1701203204398029

**Comment by mattroe** [comment]
Needs a definition of mapping and statuses
