### ISSUE TITLE
Support tool button that allows the download of a list of audit admins/jurisdiction managers by org

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/arlo#1854]
I need a support tool button that allows me to download a list of audit admins by org.

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/C01F2CH62TS/p1694529745833549?thread_ts=1694529745.833549&cid=C01F2CH62TS

**Comment by ginvdr** [comment]
Sending communications to audit admins or customer service surveys to JMs would be the primary use for this list. JMs would also need some information with a date stamp.  For example, all JM's with audits from x date to x date.
