### ISSUE TITLE
Contest totals by batch from ES&S CVR files (for RI and PA)

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/arlo#1866]
The process of creating batch totals from ES&S has been a manual process outside of Arlo that has inconsistently been performed. Ultimately, this process could be solved outside of Arlo through support users, but ideally Arlo can auto-generate these files for jurisdictions directly.

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/C01F2CH62TS/p1701963567937669?thread_ts=1701963567.937669&cid=C01F2CH62TS

**Comment by arsalansufi** [comment]
Per in-person discussion, we may want this to look different for RI and PA than it does for GA, where we generate and provide to users both ballot manifests and candidate-totals-by-batch files. We know that GA does a good job of double checking the generated ballot manifests but don't think that everyone will.
