### ISSUE TITLE
Update ES&S CVR parsing to support latest format (as seen in Washington's Thurston County)

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/arlo#1883]
https://votingworks.slack.com/archives/C013V6CT9H9/p1708479181164829

Washington has since deleted the relevant audit data, so we don't have access to a sample file from Thurston County. But reading the above Slack post, the file format appears to mirror the latest file format seen in Rhode Island, which we've accounted for in our batch inventory CVR parsing logic. The new format is actually simpler. The CVR file contains all the relevant info that we need; information is no longer spread across a CVR file and one or more ballots files.

We should update our ballot comparison audit CVR parsing logic to handle this new file format, too.

Sample file from Rhode Island: [COVPPPTest.xlsx](https://github.com/votingworks/arlo/files/15101413/COVPPPTest.xlsx)

**Comment by ginvdr** [comment]
WA reached out this week to make sure this is on our radar and requested that it be complete by the end of June.  Some files can be found here: https://votingworks.slack.com/archives/CKCVA0F9S/p1715087828353039.  One is a CVR and the other is the steps Thurston has been taking to convert them to the old format themselves.

**Comment by arsalansufi** [comment]
These ES&S files are supported via the combo of:
- https://github.com/votingworks/arlo/pull/1950
- https://github.com/votingworks/arlo/pull/1952
- https://github.com/votingworks/arlo/pull/1954
- https://github.com/votingworks/arlo/pull/1960

We could still do more to improve, but I'm going to open a new issue to track that work
