### ISSUE TITLE
Add a checkmark to the batch inventory tool after a JM has downloaded

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/arlo#1913]
Feedback from a GA county in our office hours call right now - in the batch inventory, the steps check off when you've completed the upload election results and inventory batches steps but not the download audit files... and while we think it's intuitive that you'd know you downloaded them, he downloaded twice b/c he didn't have the visual queue.

Issue automatically created from Slack feedback reported by ginny: 
https://votingworks.slack.com/archives/C01F2CH62TS/p1710859930488259

**Comment by ginvdr** [comment]
I think this was resolved when the select voting system step was added.
