### ISSUE TITLE
Incorporate ballots that haven't been counted until after audit launches

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/arlo#1928]
For batch comparison, Arlo isn't looking at total number of ballot discrepancies which could be inflating the p-value.  This is a Mark L flag, we should start collecting the number of "other" ballots essentially.  And doing so, may result in Arlo saying there are more ballots than expected b/c +1-3 happens and now allow the entry of the totals.

Issue automatically created from Slack feedback reported by ginny: 
https://votingworks.slack.com/archives/C01F2CH62TS/p1712758560619089

**Comment by ginvdr** [comment]
More context: https://votingworks.slack.com/archives/CKCVA0F9S/p1728670752890309

**Comment by ginvdr** [comment]
And more: https://votingworks.slack.com/archives/CKCVA0F9S/p1728671574682849
