### ISSUE TITLE
Provide an in-product solution for the case that a physically combined batch is selected

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/arlo#1932]
I don't fully understand this problem or the workaround that Mark came up with in the field but at least wanted to document it.

https://votingworks.slack.com/archives/C013V6CT9H9/p1712704071287439?thread_ts=1712701354.438949&cid=C013V6CT9H9

https://docs.google.com/document/d/1eio3nKzbfHID9sjlG0I92NJ0YaLswVcDp2EFo4uIuds/edit?disco=AAAAq0ybV3s

**Comment by ginvdr** [comment]
More context: https://votingworks.slack.com/archives/CKCVA0F9S/p1717596026680309
