### ISSUE TITLE
Make it possible to run multiple instances of the Arlo background worker

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/arlo#1934]
So that one audit's background processing doesn't have to block another's. This past audit season, OC's CVR processing, which can take on the order of an hour of background processing, almost coincided with GA's audit launch (audit launch requires background processing for sample size calculation).

**Comment by benadida** [comment]
I want to call out that this is a risky piece of work that requires thinking carefully about how to prevent performing background jobs multiple times, how to recover from a failed job,etc.

**Comment by jonahkagan** [comment]
Another potential workaround would be to allow Support to cancel a long-running job
