### ISSUE TITLE
Make sure that our Mailgun integration for Arlo login codes meets Gmail and Yahoo's latest email security requirements

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/arlo#1941]
https://votingworks.slack.com/archives/CKCVA0F9S/p1705000893607729

**Comment by jonahkagan** [comment]
Confirmed that we have SPF and DKIM authentication set up for our Mailgun integration. The new changes are that DMARC will also be required by Gmail for senders sending 5k emails per day (which definitely doesn't apply to us).

If we want to set up DMARC, we optionally can, but it's not gonna be required. Here's a guide to do that: https://www.mailgun.com/blog/deliverability/implement-dmarc/. Tagging @benadida in case he wants to do that.

**Comment by benadida** [comment]
thanks! I will put it on my todo without great urgency since it doesn't seem required.
