### ISSUE TITLE
Explore just using the file that GA counties routinely upload in addition to the xml file in the batch inventory tool

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/arlo#1944]
Context: The batch audit file preparation tool (referred to as the batch inventory tool in the code) is a tool that helps jurisdictions (primarily in Georgia right now) prepare the files necessary for a batch audit (a ballot manifest and a candidate totals by batch file) from their CVR files.

Georgia uses Dominion, and to generate the necessary batch audit files for a Dominion user, we need two CVR/CVR-adjacent files: a CVR CSV and tabulator status XML.

For the tabulator status XML, we support one particular format, but we've frequently seen Georgia jurisdictions upload a different XML file, that seems to also contain what we need. To minimize support burden, let's just support this alternative file as well.

More context and sample files: https://votingworks.slack.com/archives/C022U9ZN7EV/p1719239529999249 (read the thread for details)

I'd recommend using the exact audit and jurisdiction in the above link for your dev/testing.

The relevant point in the jurisdiction manager UI for reference:

| 1 | 2 | 3 |
| -- | -- | -- |
| ![Image](https://github.com/user-attachments/assets/23bfbbe6-1484-43d1-8dfa-71f23456caec) | ![Image](https://github.com/user-attachments/assets/f40ff075-c0e6-4004-88e5-bbafc5bd3a99) | ![Image](https://github.com/user-attachments/assets/c2e53155-e2cd-45fe-b872-f921a66f2100) |

**Comment by ginvdr** [comment]
More context and files https://votingworks.slack.com/archives/C022U9ZN7EV/p1719239529999249
