### ISSUE TITLE
Batch Inventory Tool - improve instructions for the inventory process through downloading and uploading audit files

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/arlo#1946]
Batch Inventory Tool - improve instructions for the inventory process through downloading and uploading audit files. This may also require a flow adjustment.  Many GA counties are trying to upload the inventory sheet into Arlo versus the ballot manifest.

Issue automatically created from Slack feedback reported by ginny: 
https://votingworks.slack.com/archives/C01F2CH62TS/p1718390657209679

**Comment by jonahkagan** [comment]
Looking at this flow, I'm not sure what instructions could make it clearer that you're not supposed to upload the batch inventory sheet into Arlo where it asks for the ballot manifest. But I think @ginvdr's suggestion is probably the best solution here:

> An error message for when a batch inventory sheet is uploaded to go back to the tool and download the correct files would be helpful too!

**Comment by kshen0** [comment]
https://github.com/votingworks/arlo/pull/2021
