### ISSUE TITLE
Clean up GA hashing script/runbook

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/arlo#1978]
https://docs.google.com/document/d/11EEgMBJ7C7fKaKjYD2RoWTSZwIdmZdE4gBtrGNzptFk/edit?usp=sharing

**Comment by jonahkagan** [comment]
@arsalansufi what needs cleaning up?

**Comment by arsalansufi** [comment]
I'll own this @jonahkagan! At the bare minimum, I need to update [this doc](https://docs.google.com/document/d/11EEgMBJ7C7fKaKjYD2RoWTSZwIdmZdE4gBtrGNzptFk/edit?usp=sharing) and the corresponding branch to reference the new audit ID and election date, e.g., https://github.com/votingworks/arlo/commit/6e5546ae714aef5494b9c5a24c510bb514a4d458

Though ideally, I'm going to make some other improvements to make this more foolproof

**Comment by arsalansufi** [comment]
Did the bare minimum of updating the audit ID and ZIP file name in the script: https://github.com/votingworks/arlo/commit/9d9ab7b4f26497f16522962083ffb745b1de1e42

And updated the runbook: https://docs.google.com/document/d/11EEgMBJ7C7fKaKjYD2RoWTSZwIdmZdE4gBtrGNzptFk/edit?usp=sharing
