### ISSUE TITLE
Investigate potential bug in batch inventory ES&S file parsing

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#2037]
https://github.com/votingworks/arlo/pull/2030#discussion_r1824896387

Add tests for es&s logic in batch inventory tool. Fix and/or make followup issues for any bugs or missing features compared to the hart/dominion implementations

**Comment by carolinemodic** [comment]
Other things to note: 
- ES&S batch inventory support seems to only allow for handling of vote for one contests
- ES&S batch inventory support seems to always filter out write ins
