### ISSUE TITLE
Ensure sampling is reproduceable

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#208]
For some reason, the code on arlo-bleeding-edge and the on arlo-prod are sampling different ballots with the same seed? We didn't deliberately change anything that should have caused this, so we need to figure out what *did* change and decide from there what to do.

One hypothesis: we might be treating the random seed as a string on bleeding-edge rather than an integer as we do on prod, which may cause the consistent sampler to sample differently.

Being able to reproduce the same sample of ballots as long as you're using the same seed is really important, so we want to track this down ASAP.

**Comment by umbernhard** [comment]
Update on this: Arlo produces different samples even on the same branch with the same seed. I'm not sure what's up here. Perhaps the way the seed is being cached is modifying it when it gets passed to the sampler? @benadida @eventualbuddha thoughts? 

The sampler is deterministic (see the tests), so it shouldn't produce different outputs from the same inputs...
