### ISSUE TITLE
Change ASN "completion in 1 round" estimate to an integer

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#213]
Arlo currently displays the chance that a sample size equal to the the ASN will complete in one round of auditing as a decimal (see screenshot) - we should round down to the nearest integer instead.

Example: Change "58.23424445537" to "58"

![Current behavior:](https://zube.io/files/votingworks/bc8ca8305bccc80e75d3afb3427950b4-screen-shot-2019-11-29-at-11-59-10-am.png "Current behavior")

**Comment by umbernhard** [comment]
@mcchilders could you provide example input that gives you this behavior?

**Comment by umbernhard** [comment]
I think this is an issue on the frontend, not the backend, fwiw.

**Comment by mcchilders** [comment]
Example is in the description - the "57.99999999999%" is what should read "57%" instead. @MorganLove is this something you can fix on the frontend or do you need back end changes?

**Comment by eventualbuddha** [comment]
Found an example:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/1938/70081695-e1d42380-15bd-11ea-9601-5907938cbf39.png">
