### ISSUE TITLE
Label sheets and placeholder sheets are outputting duplicates

### ISSUE THREAD

**Issue by umbernhard** [votingworks/arlo#217]
When a user downloads the labels and placeholder sheets, the same ballot is showing up multiple times (see attached images). 
[Round 1 Placeholders.pdf](https://github.com/votingworks/arlo/files/3908968/Round.1.Placeholders.pdf)
[Round 1 Labels-1.pdf](https://github.com/votingworks/arlo/files/3908969/Round.1.Labels-1.pdf)

![image](https://user-images.githubusercontent.com/2686765/69923432-d1636200-1472-11ea-88d9-f3f05726754d.png)

**Comment by MorganLove** [comment]
This is actually coming from the `/ballot-list` endpoint. It's returning duplicates for me, rather than quadruplicates like you're showing, though. @eventualbuddha any ideas?

**Comment by eventualbuddha** [comment]
My first thought is a bad join. This is the query: https://github.com/votingworks/arlo/blob/07929acba12bbf4a55ea9eb6b1defb03c60eed66/app.py#L622-L626.

@benadida, do you know offhand why this would produce duplicates? Here's the SQL for it:

```sql
SELECT audit_board.id AS audit_board_id, audit_board.jurisdiction_id AS audit_board_jurisdiction_id, audit_board.name AS audit_board_name, audit_board.member_1 AS audit_board_member_1, audit_board.member_1_affiliation AS audit_board_member_1_affiliation, audit_board.member_2 AS audit_board_member_2, audit_board.member_2_affiliation AS audit_board_member_2_affiliation, batch.id AS batch_id, batch.jurisdiction_id AS batch_jurisdiction_id, batch.name AS batch_name, batch.num_ballots AS batch_num_ballots, batch.storage_location AS batch_storage_location, batch.tabulator AS batch_tabulator, sampled_ballot.round_id AS sampled_ballot_round_id, sampled_ballot.jurisdiction_id AS sampled_ballot_jurisdiction_id, sampled_ballot.batch_id AS sampled_ballot_batch_id, sampled_ballot.ballot_position AS sampled_ballot_ballot_position, sampled_ballot.times_sampled AS sampled_ballot_times_sampled, sampled_ballot.audit_board_id AS sampled_ballot_audit_board_id, sampled_ballot.vote AS sampled_ballot_vote, sampled_ballot.comment AS sampled_ballot_comment, sampled_ballot.ticket_numbers AS sampled_ballot_ticket_numbers
FROM audit_board, batch, sampled_ballot
WHERE batch.id = sampled_ballot.batch_id AND sampled_ballot.jurisdiction_id = %(jurisdiction_id_1)s AND sampled_ballot.round_id = %(round_id_1)s ORDER BY audit_board.name, batch.name, sampled_ballot.ballot_position
```

**Comment by benadida** [comment]
It looks like that query is not constraining the `AuditBoard` table at all. I think we should add:

```
.filter(SampledBallot.audit_board_id == AuditBoard.id)
```

**Comment by eventualbuddha** [comment]
Ah, whoops. That'd do it. PR incoming.
