### ISSUE TITLE
Allow for multiple targeted contests in audit setup UI

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#221]
User story: 
As an audit administrator I want to target multiple contests so that I can audit more of the ballot in the same workflow, without having to run separate audits.

Description:
To target multiple contests, we need to allow users to input contest data for multiple contests. This means duplicating all the fields highlighted in the red square in the screenshot below for each additional contest. The simplest way to do this is probably to add a second link underneath "Add a new candidate/choice" (circled in red) that says "Add another targeted contest" When clicked, it should add another set of the contest fields above the link - the link should then appear at the end of this new set of contest data fields, and so on.
![Multiple Targeted Contests.png](https://zube.io/files/votingworks/102dda9e7082d7f1165665f608cc6846-multiple-targeted-contests.png)

Conditions of Acceptance:
- The "Contest Info" header(s) should now increment the way the candidate/choice labels do (Contest 1 Info, Contest 2 Info, etc.)
- The Contest Name help text ("Enter the name of the contest that will drive the audit.") should be edited to read "Enter the name of the contest you wish to target for the audit."
- Text in the style of "Add a new candidate/choice" should appear directly below it, and reads "Add another targeted contest"
- When the user clicks "Add another targeted contest," another set of Contest info fields (e.g. everything from "Contest 2 Info" header all the way to "Add another candidate/choice") will appear directly below the first set
- Focus should be on the newly added Contest Name field for Contest 2 (this means the rest of the fields will likely flow down past the fold when they are added, which is fine - the user shouldn't be autoscrolled to the end of the fieldset)
- The "Add another targeted contest" link should always appear at the end of the fieldset for the last targeted contest on the page
- The user should be able to add as many additional targeted contests as they want
- Text that reads "Remove Contest x" should appear below each contest info fieldset once there are two or more fieldsets present
- When clicked, the "Remove Contest x" should remove the associated fieldset from the page 
- Any validation performed on the first contest info data set should be performed on the subsequent sets, although note that each contest should be validated separately (e.g. when you check that the sum of all the votes is less than or equal to the number of ballots times the number of votes allowed, that check needs to be per contest, not across contests)

**Comment by MorganLove** [comment]
@mcchilders We actually already have all this supported in the frontend, with the relevant code commented out until the backend supports it.

@benadida Do you remember what was needed on the backend to support this?

**Comment by benadida** [comment]
@MorganLove yeah we've got a solid chunk of work to do on the backend and I think it's reflected in #222, though not sure yet if that's enough. This feels like a good ticket to do some pairing on!
