### ISSUE TITLE
Add ballot interpretations to audit report

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#239]
**User story:** As an audit admin I want a record of how each audited ballot was interpreted by the audit board, so that I can determine why any discrepancies may have occurred (e.g. data entry error on the part of the auditors, different interpretations of a ballot, etc.)

**CoAs:**
- When the audit admin selects "online" audit board data entry, the audit report should contain:
-- A row for each ballot that was sampled for audit (the sampled ballot data already appears in a single row, comma-separated, in the current report so that data identifying the sampled ballots can be repurposed here)
-- Which round(s) the ballot was sampled in (at least one, possibly more than 1) and the ticket numbers for each time it was sampled (e.g. something like - "Round 1: 0.0123, 0.0234" would indicate that the ballot was sampled twice in Round 1; "Round 1: 0.0123, Round 2: 0.0234" would indicate that the ballot was sampled once in Round 1, and once in Round 2)
-- Whether data was entered for that ballot yet, since ballots are sampled prior to the audit board entering data about them (Audited/Not audited)
-- If audited, what data was entered by the audit board. This could be: 1 or more candidate/choice selections OR no consensus/audit board can't agree OR ballot not found OR blank vote/no mark. If not yet audited, this field can be blank.
-- An indication of whether this is the initial entry or an edited (re-audited) entry for the ballot, since we now give audit boards the ability to go back and correct entries within a particular audit round. In either case, the most recent interpretation should show.
-- Any comments that were entered by the audit board for that ballot.

Note: I realize this is *a lot* of data, so if this requires us to move from .csv to .xls and start using tabs, that's fine with me. Whatever's cleanest/clearest.

**Comment by jonahkagan** [comment]
As discussed with @mcchilders, we don't currently record when a ballot is re-audited in the database, so leaving that out of the audit report for this task. We can revisit later.
