### ISSUE TITLE
Authentication Flows with auth0

### ISSUE THREAD

**Issue by benadida** [votingworks/arlo#250]
Authentication flows against auth0 for AA and JA.

AA should use 2fa, JA should use email magic link.

APIs between our front-end and back-end:
* the backend should maintain a cookied-session
* `GET /auth/me` should return to the client a JSON structure with user information or a message that the user is not logged in.
* `POST /auth/dev/set-user` is a dev-only call that lets the front-end just set a user for the purpose of testing and development. The data structure post'ed is the same as the one received from `/auth/me`.

The data structure for `/auth/me` should be:

```
{
  type: "auditadmin",
  email: "clerk@county.gov"
}
```

**Comment by MorganLove** [comment]
Would we be able to have the audits associated with a particular audit admin included with the `/auth/me` endpoint?

```
{
  type: "admin",
  userid: "email:clerk@county.gov",
  name: "Jane Smith",
  audits: [
    "a97uh4r9uhif08o92fh", // :election_id
    "02wjfghj028jhfj208f3", // :election_id
  ],
}
```

**Comment by mcchilders** [comment]
All audits can/will be associated with a particular admin, yes.

**Comment by benadida** [comment]
not likely in the same API call, but yes the feature of associating audits with an owner for sure.

**Comment by mcchilders** [comment]
Waiting on the back-end work for this (see votingworks/arlo#259 but the front end is done.

**Comment by benadida** [comment]
@MorganLove makes sense to have those audits returned in that API call yes.

**Comment by benadida** [comment]
we don't have the `/auth/dev/set-user` call yet. Let's see if we need it. The `/auth/me` call is now on staging.
