### ISSUE TITLE
Create audit admin authentication workflow

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#260]
User Story: As an election administrator I want to be able to log in to my audit admin dashboard easily and securely.

Conditions of acceptance:
- Within Auth0, VW staff should be able to designate a new user and assign them the role of "audit admin" for a particular state/client
-- An email address & state/client should be the minimum requirement for defining a new audit admin; name & other fields fine but optional
- Designating a new user with the role of audit admin in Auth0 should trigger a welcome email to that user's email address with instructions to the user on how to set up his/her password & 2FA
-- The setup invitation should expire at a reasonably short interval - 48 hours is preferred, talk to Monica if that doesn't work.
-- A new setup invitation should be able to be reissued in the event that the user doesn't set up her credentials before it expires (this should be standard in Auth0, but let's confirm)
-- For the first pass at 2FA, let's use a software token. Auth0 supports both Google Authenticator & Duo out of the box; agnostic on which we use but Google authenticator is prob in more widespread use.
- Once the user has setup his/her credentials, logging in successfully with the correct password and 2FA token through the Auth0 widget should take the user to the audit admin dashboard associated with her state/client 
- If a user attempts to log in via the Auth0 widget using an email address that is not designated with the role of audit admin, or has not yet set up his/her credentials, no access shall be given
-- If there is a way to differentiate the error messages between these two cases (e.g. so we could say "unrecognized email address" in the first instance and "you haven't set up your account yet, please follow the instructions" in the second, bonus points!

Open Questions:
- Because we may need all the user -> state/client mappings (along with the audit -> state/client mappings) on our end, it may be simpler to house/manage the actual user data within Arlo, and just use Auth0 for the auth. If that's the case, let Monica know and we can update the card.
- Do we need to enforce an auth timeout?

Notes:
- The Auth0 interface lets us customize many things - the welcome email text, the logo on the login widget, etc. Don't worry about that stuff right now - once our Auth0 account is setup & working, Monica can go in and edit the look/feel of that stuff.
- Note that multiple users may be given the audit admin role for the same state/client; this is by design, since an audit cannot have a single point of failure and must go on even if the main audit admin is out sick, for example.

**Comment by MorganLove** [comment]
@benadida When we create a new user in Auth0, just confirming that it will be automatically populated on the user's first login via Auth0? I think we can do this via this endpoint: https://auth0.com/docs/users/search/v3/get-users-endpoint

**Comment by benadida** [comment]
OK, this functionality is merged as votingworks/arlo#250 . Here's how it works:

- we have the user database
- we outsource authentication to Auth0
- when the user comes back, we check that their Auth0 email auth matches what we have
- then we designate them logged in with our session.
