### ISSUE TITLE
Clean up API after online/offline split

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/arlo#271]
@eventualbuddha This is what gets sent and what prompts the calculation for the next round. It definitely is odd, yes. It's leftover from before we separated the offline and online data entry flows, and should be updated to something that makes more sense. I didn't even realize this was still done this way until I was walking through and documenting, haha.

_Originally posted by @MorganLove in https://github.com/votingworks/arlo/pull/266_

**Comment by jonahkagan** [comment]
No longer relevant
