### ISSUE TITLE
AA global dashboard nav

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#278]
*User story:*
As an AA I want to be able to get to the various parts of my dashboard quickly & easily so that I can get to the various functions.

*Conditions of Acceptance:*
All pages in the AA dashboard have the same basic navigation options:
- Links across the page header that go to the following:
--- New Audit (goes back to Create New/View Existing)
--- View Audits (goes back to Create New/View Existing)
--- Audit Setup (Goes to the "participating jurisdictions" screen, which is the first in the audit setup workflow)
-- Audit Progress (Goes to the "audit progress" screen)
-- VW logo/Arlo name in the top left (links to "audit progress" screen )
-- Log out icon/label in the top right, logs the user out and returns them to the login screen)

*Wireframe:*
![Screen Shot 2020-02-28 at 12.04.50 PM.png](https://zube.io/files/votingworks/07baeaccdbe58e9f81556efaf2243698-screen-shot-2020-02-28-at-12-04-50-pm.png)

**Comment by MorganLove** [comment]
@mcchilders 

If we take the suggestions from votingworks/arlo#277 then we can pair this ticket down to just be breadcrumbs.

**Comment by mcchilders** [comment]
@MorganLove updated with new wireframes
