### ISSUE TITLE
AA audit status box

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#279]
*User story:*
As an AA I want to be able to see the status of my audit at-a-glance, so that I can keep tabs on what needs to be done.

*Background:*
This grey box at the top is the "audit status" box - it is present on every page in both the AA and JA dashboards, and contains basic info about the audit. Principally, this info is about:
- Overall audit status (not started, in progress, complete)
- Whether the audit setup steps are complete (precursor for launching the audit)
- How many jurisdictions have completed their work in various audit phases (e.g. before the audit starts - how many have uploaded required files, during the audit - how many have completed the ballots assigned to them in the round

*Conditions of Acceptance:*
On the AA dashboard screens, this box contains:
- An indication of the audit status (e.g. "The audit has not started." or "Round 1 of the audit is in progress." or "The audit is complete.")
- Before the audit has started, and indication of whether the audit setup steps have been completed (e.g. "Audit setup is not complete." or "Audit setup is complete."
- Before the audit has started, an indication of how many of the participating jurisdictions have uploaded the files they need to upload for the audit to start (not shown here, requires data from this page to show, but adding for clarity).
- A button to download the audit report (hidden until the audit is started).

*Wireframe:*
Prior to audit launch:
![Screen Shot 2020-02-28 at 12.04.27 PM.png](https://zube.io/files/votingworks/abaf6d8c12fe8a8d1924bb5e79653f7f-screen-shot-2020-02-28-at-12-04-27-pm.png)
After audit launch (includes audit report download button):
![Screen Shot 2020-02-28 at 12.04.50 PM.png](https://zube.io/files/votingworks/2215d889db7649fdbdc11d7797d98a18-screen-shot-2020-02-28-at-12-04-50-pm.png)

**Comment by mcchilders** [comment]
@MorganLove updated the wireframes to show new design. Here are the complete list of statuses for the AA dashboard:
Overall audit statuses ... "The audit has not started." "Round <X> of the audit is in progress." "The audit is complete."
Audit setup statuses (only shown prior to audit launch) ... "Audit setup is not complete." "Audit setup is complete."
Jurisdiction upload statuses (only shown prior to audit launch) ... "<X> of <total # of jurisdictions> jurisdictions have completed file uploads."
Jurisdiction progress statuses (only shown after audit launch & before completion) ...<X> of <total # of jurisdictions> jurisdictions have completed Round <Y>."

**Comment by MorganLove** [comment]
@mcchilders Just wanting to clarify some points between this and the Balsamiq mockups. I think you might have wrote 'audit launch' in the above post when you meant 'audit start' in a couple spots.

For example, in this series of statuses you have the # of jurisdictions which have completed file uploads (I'm assuming the ballot manifests) marked as only shown prior to audit launch. But in the Balsamiq mockups you have the audit launch happening before the stage at which jurisdictions can upload those ballot manifests. But the jurisdictions select sample size and number of audit boards, and upload the ballot manifest, before the audit starts and the first round begins. So it makes sense that the status of how many jurisdictions have uploaded ballot manifests would only show after the launch but before the first round starts.

Also, you've also got "Audit setup is complete" as a status that only shows prior to audit launch, but at what point is the setup complete but the audit isn't launched? From the Balsamiq mockups it looks like launching the audit is what completes the setup. But this status looks like it would indicate that the setup is complete and the audit is launched, but isn't started yet (the same stage mentioned above where the jurisdictions are uploading their ballot manifests).

Does that make sense, or am I misunderstanding the flow here?

**Comment by mcchilders** [comment]
One merge conflict that needs to be resolved, then ready to go!
