### ISSUE TITLE
Enforce SSL on staging/prod/latest (everywhere)

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#324]
We need to make sure we're redirecting anything from http -> https on any of our Arlo domains (in part because the Auth0 stuff expects it.)

https://vx-arlo-staging.herokuapp.com/
https://vx-arlo-latest.herokuapp.com/
https://arlo.votingworks.app

**Comment by eventualbuddha** [comment]
@benadida are we using something like cloudflare where we can just turn this on? Or do we have to do it at the application level?

**Comment by mcchilders** [comment]
@benadida Can you weigh in on Brian's q here, please?

**Comment by benadida** [comment]
> @benadida are we using something like cloudflare where we can just turn this on? Or do we have to do it at the application level?

We're just using Heroku for now -- even if that changes, I think we should have a simple redirect to the right configured hostname, including protocol.

So we already have `ARLO_HTTP_ORIGIN` as a required parameter, if the service finds that it's being requested at a different origin, it should redirect to the specified origin.

**Comment by eventualbuddha** [comment]
One nice thing is that [the `.app` TLD requires SSL](https://stackoverflow.com/questions/50258202/how-does-google-force-https-on-their-app-tld). The heroku-based ones will still benefit from this, though.
