### ISSUE TITLE
make sure we have audit_name and election_name as separate fields in DB and API

### ISSUE THREAD

**Issue by benadida** [votingworks/arlo#345]

**Comment by MorganLove** [comment]
We also need to have an endpoint for returning whether or not a given string is valid as a unique audit_name or not.

**Comment by jonahkagan** [comment]
Could that be an error from the endpoint that creates audits when you try to create an audit? Or do you want it to be something you can validate before trying to create the audit?

**Comment by benadida** [comment]
> Could that be an error from the endpoint that creates audits when you try to create an audit? Or do you want it to be something you can validate before trying to create the audit?

+1 to this, @mcchilders had mentioned in a previous ticket how an error on creation would be just fine for now.
