### ISSUE TITLE
add a single-page vs. multi-jurisdiction flag to election model and API

### ISSUE THREAD

**Issue by benadida** [votingworks/arlo#358]
Right now, we're assuming that elections created by authenticated users are multi-jurisdiction, and otherwise single-page flow. Let's make that explicit in the data model and API.

**Comment by eventualbuddha** [comment]
What's the medium/long-term goal for these two flows? Is having two distinct flows desirable? It's definitely an increased maintenance burden and source of complexity. Are we sure it's worth it?

**Comment by eventualbuddha** [comment]
> What's the medium/long-term goal for these two flows? Is having two distinct flows desirable? It's definitely an increased maintenance burden and source of complexity. Are we sure it's worth it?

@mcchilders says yes, we do want this for now.
