### ISSUE TITLE
Require unique jurisdiction names within an audit, and unique batch names within a jurisdiction

### ISSUE THREAD

**Issue by jonahkagan** [votingworks/arlo#389]
These constraints should be implemented with db indexes.

These endpoints will need to be updated with error messages:
- PUT /election/<election_id>/jurisdiction/file
- PUT /election/<election_id>/jurisdiction/<jurisdiction_id>/manifest

The frontend will need to receive and display these error messages.

**Comment by eventualbuddha** [comment]
These APIs are async, so the frontend is going to have to check the associated `GET` endpoints for a file processing error.
