### ISSUE TITLE
This line may cause the server to crash in certain kinds of elections.

### ISSUE THREAD

**Issue by umbernhard** [votingworks/arlo#390]
https://github.com/votingworks/arlo/blob/e35bf95d4f26f35692492b63dbe8771fa3c6070d/arlo_server/rounds.py#L135

The backend may not return a full set of sample size options, for example in the case of multi-winner elections. I think this will cause the server to crash due to a `KeyError`, but  I can't verify because I can't run a full election right now.

**Comment by mcchilders** [comment]
This happens specifically in multi-winner right now.

**Comment by umbernhard** [comment]
This was closed in an old PR.
