### ISSUE TITLE
500 server error in /audit/report plus popup about json syntax error

### ISSUE THREAD

**Issue by nealmcb** [votingworks/arlo#510]
This may be my fault, due to some WIP local sample-size algorithm changes from [Arlo+Athena](https://github.com/nealmcb/arlo/tree/athena-routes), and/or low-priority, and/or hard to reproduce, but in case it is of use:

After going to 4 rounds in an audit, and presumably wrapping it up at the end, I got a spinner in the web UI, and noticed a notification popup about a json syntax error.

Via the Chrome DevTools debugger console I retrieved the error:

`UserContext.tsx:31 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0`

Then I noticed a server error in the Terminal:

     INFO:werkzeug:127.0.0.1 - - [07/May/2020 22:06:56] "POST /election/2774617b-b95e-4679-8fb4-1d6e2ddcfbf0/jurisdiction/d42bbb9d-3c2c-4b98-84bc-597102778278/4/results HTTP/1.1" 500 -

I'm no React/Javascript developer, but it would seem useful to catch the 500 error before trying to parse JSON in the response, of that is what is going on there.

I can probably dig out more info if that would be helpful.

**Comment by umbernhard** [comment]
I believe this issues has been resolved in later versions of Arlo. Closing.
