### ISSUE TITLE
Changes for ABs w/o ballots

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#583]
*User Story:*
As an admin, I don't want audit boards without any ballots assigned to them to have to participate at all, so that they can essentially "sit out" the round entirely.

*Background:*
This comes out of our experience in MI with people accidentally setting too many audit boards, and then having some of them go unused. We had previously assumed all audit boards would get used, but now we know that isn't always the case.

*CoAs:*
1. ABs w/o any ballots assigned in the current round are not asked/required to log in (no credentials)
2. " should not be required to sign off for the round to complete
3. The AB credentials PDF should list those audit boards, but indicate there are no ballots assigned to that board rather than providing them credentials (can be done on a single page for multiple boards - no need to waste multiple pages of paper)
4. The progress bars for those ABs on the JA flow should show "no ballots to audit"

**Comment by jonahkagan** [comment]
COA #2 was implemented here: https://github.com/votingworks/arlo/pull/577
