### ISSUE TITLE
Deploy data model change - Overvote handling

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#586]
*User story:*
As an admin I want Arlo to be able to determine if something is an overvote or not and count it accordingly, so that AB members can worry about just reporting exactly what they see on the ballot.

*Background:* (Please see the epic description for context!)

*CoAs:*
- Arlo's data model should support recording all candidate selections as entered by the audit board and, additionally, how those selections were adjudicated (Valid/Overvote)

*Open questions:* 
Do we need to do a migration? I don't think we're worried about preserving any of the data except MI, and we can keep their instance of Arlo locked for as long as we need it (likely not more than a couple weeks) and then trash it.

**Comment by jonahkagan** [comment]
Discussed and decided to skip the migration and make a new deploy for RI.
