### ISSUE TITLE
API for multi-jurisdiction offline ballot data entry

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#652]
If you're using offline data entry:
- Audit board only retrieves and tallies, does not do online data entry.
- Don't need to generate credentials
- Can't require AB signoff to complete a round
Also need to:
- Make sure audit report shows aggregates only, not ballot by ballot data. (should just be leaving the ballot by ballot data out?)

**Comment by jonahkagan** [comment]
```
POST /election/:electionId/jurisdiction/:jurisdictionId/round/:roundId/results
{
  "contest-id-1": {
    "contest-1-choice-id-1": 10,
    "contest-1-choice-id-2": 15,
    ...
  },
  "contest-id-2": ...
}
```
