### ISSUE TITLE
Regression: audit doesn't complete, sometime between 37989d49 and bbed6cc1

### ISSUE THREAD

**Issue by nealmcb** [votingworks/arlo#679]
I've run successful audits against this commit:

    37989d49 2020-07-28 E (tag: bravo-worked) Fix default database URL username/password (#660)

with a contest 750-250, margin 50%, manually entering 7 ballots (despite offline mode being set - that also seems broken...)

I get a nice report, etc.

But when I do the same audit (many times!) against this latest version of main:

    bbed6cc1 2020-08-04 E (main) Add contests and settings endpoints for jurisdiction admins (#668) [GitHub]

it all seems to run well, and the audit board is told they're done, but for the audit administrator, the audit is never determined to be complete ("0 of 1 jurisdictions have completed Round 1") and I can't get any reports, etc.

**Comment by umbernhard** [comment]
I can't verify this either. Did you upload manifests as the jurisdiction?

**Comment by nealmcb** [comment]
I also no longer see this as of d6181d3a, so it got fixed somewhere along the way.
