### ISSUE TITLE
Regression: offline mode is broken - always asks for individual ballot entry

### ISSUE THREAD

**Issue by nealmcb** [votingworks/arlo#681]
In May offline mode worked fine and was an easy way to run tests.
Now the setting seems to be ignored, and jurisdiction administrators are always asked to set up audit boards.

**Comment by umbernhard** [comment]
@nealmcb I'm not able to replicate this issue. Once I get past the number of audit boards, it goes right to offline entry. We may want to not ask them how many audit boards they have, but that's a different problem.
