### ISSUE TITLE
Require jurisdiction data to calculate # of batches that need to be audited

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#717]
Enforce that all jurisdiction uploads must be complete before "# of batches to be sampled" options are shown on the AA Audit Setup - Audit Review screen.
 
Until uplaods are finished, show a message "Waiting for jurisidiction data to calculate required number of batches ....

(backend: also validate that batch tallies add up to vote total from contest settings)

**Comment by jonahkagan** [comment]
@MorganLove I'm thinking that you can actually implement this on the frontend using the `/jurisdiction` response. The jurisdiction objects each have a `batchTallies` field on them which contains the file upload status.

I'll just add a small guard on the backend as well

**Comment by MorganLove** [comment]
@jonahkagan So the current type for the `/jurisdiction` response is:

```
export interface IJurisdiction {
  id: string
  name: string
  ballotManifest: IBallotManifestInfo
  currentRoundStatus: {
    status: JurisdictionRoundStatus
    numSamples: number
    numSamplesAudited: number
    numUnique: number
    numUniqueAudited: number
  } | null
}
```

So is that no longer accurate, and there's a new field like so:

```
export interface IJurisdiction {
  id: string
  name: string
  ballotManifest: IBallotManifestInfo
  batchTallies: IFileInfo // does this have any additional fields like IBallotManifestInfo has?
  currentRoundStatus: {
    status: JurisdictionRoundStatus
    numSamples: number
    numSamplesAudited: number
    numUnique: number
    numUniqueAudited: number
  } | null
}
```
