### ISSUE TITLE
Rework printed ballot retrieval list UI

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#728]
We often take the time to add further styling to these spreadsheets in Excel before printing, for clarity. It would be nice if Arlo added some of that, including:
- Alternating colors between rows
- Having a version that is "all ballots" and ones that are just the ballots for a particular audit board
- Including printable PDFs in addition to the spreadsheet version
- Remove previously audited ballots from list for clarity

**Comment by jonahkagan** [comment]
Replacing with https://github.com/votingworks/arlo/issues/1538
