### ISSUE TITLE
Hyperlinks on audit board credentials truncate if they run over the end of the line

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#801]
In the attached PDF, the hyperlink for the page is:
https://arlo-ballot-comparison--aflm46.herokuapp.com/auditboard/porous-radio-ove

While the full URL is: 
https://arlo-ballot-comparison--aflm46.herokuapp.com/auditboard/porous-radio-overbuilt-rigging

The hyperlink is being truncated at the line break for some reason. 

[Audit Board Credentials - Sample County - Ballot Comp Test 6.pdf](https://zube.io/files/votingworks/59df1f8541a8eb2fc28822449b3b18f1-audit-board-credentials-sample-county-ballot-comp-test-6.pdf)

**Comment by MorganLove** [comment]
@mcchilders it's not truncating it's wrapping, the rest of the url is on the next line. That's how it's supposed to work, unless we make the font super small or force much much shorter urls.

**Comment by mcchilders** [comment]
I understand that it's wrapping on the page - this card is about the hyperlink not respecting the wrapping, and so the URL is getting truncated so when you click it the wrong URL is opened and it shows an error (try clicking on the link, then, look at the URL)
