### ISSUE TITLE
Audit board signoff shows error?

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#802]
Of the two audit boards that I had ballots assigned to in Round 1, signing off the first audit board (which was actually Audit Board 2) went great, but when I tried to sign out the other audit board (Audit Board 1) I get this error: 

![Screen Shot 2020-10-20 at 11.16.03 PM.png](https://zube.io/files/votingworks/3e98bf32c6dbf453e4b27b29fb0d600b-screen-shot-2020-10-20-at-11-16-03-pm.png)

This is on https://arlo-ballot-comparison--aflm46.herokuapp.com/election/371716ac-1756-4a2a-a8ac-60cb60849e51/audit-board/0b394133-dc01-4155-bf61-33d06fe83a1d/signoff

**Comment by jonahkagan** [comment]
replaced by votingworks/arlo#806
