### ISSUE TITLE
Continue to show chosen sample size after audit launch

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#804]
When you launch the audit, instead of showing the sample size option you selected, it reverts back to the "waiting for jurisdiction files" behavior?
![Screen Shot 2020-10-21 at 12.31.17 PM.png](https://zube.io/files/votingworks/85296bf2e9a3413b7bc1812649583aea-screen-shot-2020-10-21-at-12-31-17-pm.png)

**Comment by jonahkagan** [comment]
this is resolved in votingworks/arlo#798
