### ISSUE TITLE
Reorder columns on AB ballot list as Tab-Batch-Ballot

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#810]
Right now it is Batch - Ballot - Tab
![Screen Shot 2020-10-21 at 3.27.37 PM.png](https://zube.io/files/votingworks/347fc85a670bcd7b648eddc4807e6b96-screen-shot-2020-10-21-at-3-27-37-pm.png)

**Comment by jonahkagan** [comment]
Probably also should add a Container column if Container provided, yes?
