### ISSUE TITLE
Add new button for "not on ballot"

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#846]
On the ballot data entry screen, we currently have a button that says "Blank vote/Not on ballot." We need to take that label back to its original form (E.g. just "Blank vote") and add a second button for "Not on ballot." Should have the same behaviors as "blank vote" - if you click this button, it clears any other votes, etc.

- Change the label back to "Blank vote"
- Add a new button for "Not on ballot" (somewhere at the bottom, wherever is fine)
- Hooking it up so that it actually records "Not on ballot" when you click it.

**Comment by jonahkagan** [comment]
I need to do some backend work for this one as well
