### ISSUE TITLE
Investigate holiday alert

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#968]
See this Slack message for the alert: https://votingworks.slack.com/archives/CKCVA0F9S/p1609187836426200

And this thread for the investigation details: https://votingworks.slack.com/archives/CKCVA0F9S/p1609208305428900

**Comment by jonahkagan** [comment]
It's likely that the weird quoting is just a JSON logging/parsing error in Flask or Sentry, since the request body in Sentry doesn't have this issue - it's only in the stack trace. This alert was most likely caused by a double click, as originally hypothesized.
