### ISSUE TITLE
Protect forms from double-click errors (audit board interface)

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#969]
Let's make sure the forms that the audit board uses to enter data don't allow double data entry via double-clicks

**Comment by jonahkagan** [comment]
Resolve this Sentry error once released: https://sentry.io/organizations/votingworks/issues/2117356002/events/5a28d8ceed7643d0bbd6e48a6315de9c/?project=5504628

**Comment by mcchilders** [comment]
Figured out that it's just in the one workflow (audit board ballot data entry/review)
