### ISSUE TITLE
Look at optimizing text space on ballot labels

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#987]
Particularly 4 lines of text on labels - can we bump the font size down to accommodate that when necessary (and not when it's not?) Or is detecting when it's 4 lines hard?

**Comment by MorganLove** [comment]
[Round 1 Labels - Autaga County - ballot polling three (1).pdf](https://zube.io/files/votingworks/b7343b9e4d0d0843b797ff875cb8ecb6-round-1-labels-autaga-county-ballot-polling-three-1.pdf)

[Round 1 Labels - Autaga County - ballot polling three (4).pdf](https://zube.io/files/votingworks/1b00d3ee01fb472a370fa9e72f61432e-round-1-labels-autaga-county-ballot-polling-three-4.pdf)

I just attached an example pdf that uses six lines based off our current code. It runs over the edge of the labels only slightly, but if I remember right, though, no audit type will have all six lines, only a max of five.

So if we shrink down the font size only by one point we can easily fit six lines, which is one more line than we currently support. If we drop it down a couple more points we can fit seven lines, but the font is pretty tiny at that point and we're getting into readability issues.

I have an idea of how to restructure the `downloadLabels` function in a way that would allow us to generate all the content for the sheets, then check the number of lines for each label, and if any of them are over six, bump down the font size then generate the labels. It'll take some refactoring, but I think it's doable.

How many lines do we want to support, and how small do we want the font to go? I'm attaching another example pdf with the seven line version to show how small it's getting.
